function result = dna_xor(base1, base2)
    % 定义 DNA 碱基的异或映射规则
    xorMap = containers.Map({'AA', 'AG', 'AC', 'AT', ...
                             'GA', 'GG', 'GC', 'GT', ...
                             'CA', 'CG', 'CC', 'CT', ...
                             'TA', 'TG', 'TC', 'TT'}, ...
                            {'A', 'G', 'C', 'T', ...
                             'G', 'A', 'T', 'C', ...
                             'C', 'T', 'A', 'G', ...
                             'T', 'C', 'G', 'A'});

    % 使用映射表获取异或结果
    key = [base1 base2];
    if isKey(xorMap, key)
        result = xorMap(key);
    else
        error('无效的DNA碱基输入');
    end
end